-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE * SUM(O.SALES_AMOUNT) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE

# SELECT *, SUM(PRICE) FROM PRODUCT GROUP BY LEFT(PRODUCT_CODE, 2);
# -- B 42000(5) 72000(10) 80000(20

# SELECT * FROM OFFLINE_SALE WHERE PRODUCT_ID IN (5, 10, 20);