-- 코드를 입력하세요
SELECT DATE_FORMAT(ONS.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, ONS.PRODUCT_ID, ONS.USER_ID, ONS.SALES_AMOUNT
FROM ONLINE_SALE ONS
WHERE YEAR(ONS.SALES_DATE) = 2022 AND MONTH(ONS.SALES_DATE) = 3
UNION ALL
SELECT DATE_FORMAT(OFS.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, OFS.PRODUCT_ID, NULL, OFS.SALES_AMOUNT
FROM OFFLINE_SALE OFS
WHERE YEAR(OFS.SALES_DATE) = 2022 AND MONTH(OFS.SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID