-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.daily_fee * (100-P.discount_rate) /100) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  P
ON C.CAR_TYPE = P.CAR_TYPE
-- 11월 1일부터 30일까지 대여 가능
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN(
        SELECT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE H.START_DATE <= '2022-11-30'
          AND H.END_DATE >= '2022-11-01'
    )
GROUP BY C.CAR_ID
HAVING 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC