-- 코드를 입력하세요

SELECT  C.CAR_ID, 
        C.CAR_TYPE, 
        ROUND(C.DAILY_FEE * ((100-P.discount_rate) / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE 
    C.CAR_TYPE IN('SUV', '세단') 
    AND P.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT H.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        WHERE H.START_DATE <= '2022-11-30'
          AND H.END_DATE >= '2022-11-01'
    )
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC

-- if duration_type 
