-- 코드를 입력하세요
SELECT  YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT(U.USER_ID)) AS 'PURCHASED_USERS', 
    -- 2021년에 가입한 회원 중 상품을 구매한 회원수 /
    -- 2021년에 가입한 전체 회원 수
    ROUND(( COUNT(DISTINCT(U.USER_ID)) /
    (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) =2021)), 1) AS 'PUCHASED_RATIO'
FROM USER_INFO U
JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)