-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE*SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE '2022-05-01' <= O.PRODUCE_DATE AND O.PRODUCE_DATE <= '2022-05-31'
GROUP BY P.PRODUCT_ID
ORDER BY P.PRICE*SUM(O.AMOUNT) DESC, P.PRODUCT_ID
-- 22 2500


# SELECT * FROM FOOD_ORDER;