WITH RECURSIVE HOUR AS(
    SELECT 0 as NUM
    UNION ALL
    SELECT NUM + 1
    FROM HOUR
    WHERE NUM < 23
)

SELECT H.NUM AS HOUR, COUNT(O.DATETIME) AS COUNT
FROM HOUR H
LEFT JOIN ANIMAL_OUTS O
ON HOUR(O.DATETIME) = H.NUM
GROUP BY H.NUM