-- 코드를 입력하세요
# SELECT SUM(PRICE)
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_USER U
# ON B.WRITER_ID = U.USER_ID
# WHERE B.STATUS = 'DONE'
# HAVING SUM(PRICE) >= 700000

SELECT WRITER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
JOIN USED_GOODS_USER
ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC
