
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M
JOIN REST_REVIEW AS R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(*) = (
    SELECT MAX(cnt) FROM 
        (SELECT COUNT(*) AS cnt 
         FROM REST_REVIEW 
         GROUP BY MEMBER_ID) AS t)
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT

