-- 종류 별로 가장 큰 물고기
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n
ON i.FISH_TYPE = n.FISH_TYPE
WHERE (i.FISH_TYPE, LENGTH) in (
SELECT FISH_TYPE, MAX(LENGTH)
FROM FISH_INFO
GROUP BY FISH_TYPE)


