-- 코드를 입력하세요
SELECT d.TITLE, d.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD d
JOIN USED_GOODS_REPLY r
ON d.BOARD_ID = r.BOARD_ID
WHERE '2022-10-01' <= d.CREATED_DATE AND d.CREATED_DATE <= '2022-10-31'
ORDER BY CREATED_DATE, d.TITLE
